table P&L_Pivot
	lineageTag: 9d887875-0e3f-47c4-aad7-082ed540ae77

	measure Vol_Units_New = sum('P&L_Pivot'[VOLUMES_IN_UNITS])
		formatString: #,0
		lineageTag: 4103c85c-9d03-4da8-a425-998cedbcd203

	measure Std_Cogs_New = sum('P&L_Pivot'[Std_Cogs_Hos_HW])
		formatString: 0.000
		lineageTag: ff713e2a-1a74-48a3-95a0-c6641de2090b

	measure Cogs_Value_Hos_HW_Measure = sum('P&L_Pivot'[Cogs_value_Hos_HW])
		formatString: 0.000
		lineageTag: 0aaa6683-bc89-4072-94de-dae826463d54

	measure Invoiced_Sales_New = SUM('P&L_Pivot'[INVOICED_SALES])
		formatString: 0.000
		lineageTag: 80406970-2a9c-4dc6-880c-e9e9030cf969

	measure FP10_Price_New = SUM('P&L_Pivot'[FP10_PRICE])
		lineageTag: 8102a44c-3eef-465b-b06a-aee4e451774f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FP10_Value_New = SUM('P&L_Pivot'[FP10_VALUE])
		formatString: 0.000
		lineageTag: 4a2d213c-82d7-41e8-99a6-316339557291

	measure Avg_Sel_Price_New = SUM('P&L_Pivot'[Avg_Selling_Price])
		lineageTag: 4170f4a0-794a-49da-a482-aeaa86f2747d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Cogs_Value_Comm_Measure = sum('P&L_Pivot'[Cogs_value_Comm])
		lineageTag: 5085aa5a-3368-4654-9965-82fd1110aa42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOURCE
		dataType: string
		lineageTag: 0e7a068a-33e8-4ffd-85ab-8764e52fe1af
		summarizeBy: none
		sourceColumn: SOURCE

		annotation SummarizationSetBy = Automatic

	column CONTRACT_ID
		dataType: double
		lineageTag: 6f978afb-6298-4a41-8d40-b1e62adb853d
		summarizeBy: none
		sourceColumn: CONTRACT_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CONTRACT_R_ID
		dataType: string
		lineageTag: d8262303-7c53-46a9-a195-199e6c201034
		summarizeBy: none
		sourceColumn: CONTRACT_R_ID

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column CURO_SUB_CONTRACT_ID
		dataType: double
		lineageTag: 39c9157e-715a-4833-b82d-170f5660aafd
		summarizeBy: count
		sourceColumn: CURO_SUB_CONTRACT_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SALES_CHANNEL_ID
		dataType: int64
		lineageTag: 91d7c69d-ec6f-4c3f-969e-a251eb313fed
		summarizeBy: count
		sourceColumn: SALES_CHANNEL_ID

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRODUCT_ID
		dataType: string
		lineageTag: 4cc6e3bd-fc47-41b7-a1c4-a43f8bd97a0d
		summarizeBy: none
		sourceColumn: PRODUCT_ID

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: dd7ad137-de5b-4716-8170-4cd9c426bbab
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column Avg_Selling_Price = DIVIDE('P&L_Pivot'[INVOICED_SALES],'P&L_Pivot'[VOLUMES_IN_UNITS],0)
		lineageTag: ffcf5248-3d4a-4698-bb4e-510d47a88b19
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Std_Cogs_Hos_HW = RELATED(Cogs_Hos_HW[TOTAL_STD_COGS_PER_UNIT])
		formatString: 0.000
		lineageTag: 1c1a6b36-129d-4afe-9c32-1529673ba9c3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Cogs_value_Hos_HW = 'P&L_Pivot'[VOLUMES_IN_UNITS]*'P&L_Pivot'[Std_Cogs_Hos_HW]
		lineageTag: 4ae84b34-4341-4bce-b896-0f2ca5c549dc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GEOGRAPHY_ID
		dataType: double
		lineageTag: 0b08ccfa-667c-4620-be78-f8d162ac7f31
		summarizeBy: none
		sourceColumn: GEOGRAPHY_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VOLUMES_IN_UNITS
		dataType: double
		lineageTag: ec554932-7a6e-4495-b74b-34d44839398c
		summarizeBy: sum
		sourceColumn: VOLUMES_IN_UNITS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column INVOICED_SALES
		dataType: double
		lineageTag: 2b4de52c-d527-4deb-bd5f-9d79d95795c1
		summarizeBy: sum
		sourceColumn: INVOICED_SALES

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FP10_VALUE
		dataType: string
		lineageTag: f704e34b-377f-4558-9a83-5a7f0206ff24
		summarizeBy: none
		sourceColumn: FP10_VALUE

		annotation SummarizationSetBy = Automatic

	column FP10_PRICE
		dataType: double
		lineageTag: 5fe3a86b-e0ba-4a70-9d1b-cba038bf598b
		summarizeBy: sum
		sourceColumn: FP10_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Std_Cogs_Comm = RELATED(DIM_PRODUCT[WEIGHTED_COGS_PER_UNIT])
		lineageTag: a39f398c-5ff2-446e-9f55-39fb1e3637c3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cogs_value_Comm = 'P&L_Pivot'[VOLUMES_IN_UNITS]*'P&L_Pivot'[Std_Cogs_Comm]
		lineageTag: 92586156-59c1-4254-8af9-e8a42bbb523d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Local6_PRODUCT_key = RELATED(DIM_PRODUCT[PROD_HIER_LOCAL_6_ID])&'P&L_Pivot'[PRODUCT_ID]
		lineageTag: 7a28daaa-509d-4589-9673-7ff12d55f416
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Column = RELATED(DIM_MEDICAL_CONTRACT_R[CONTRACT_R_NAME])
		lineageTag: f8388c5a-87d8-4758-af3d-9cc3f4239930
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Local_6 = RELATED(DIM_PRODUCT[PROD_HIER_LOCAL_6_ID])
		lineageTag: 7ea2e62c-844e-45bb-981b-21e60732a070
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Percentage_ =
			VAR per_ = SWITCH(RELATED(DIM_PRODUCT[PROD_HIER_LOCAL_5_NAME]),
			"FORTISIP COMPACT PROTEIN", 0.56,
			"FORTISIP COMPACT FIBRE",0.4,
			"FORTIJUCE",0.64,
			"FORTISIP COMPACT",0.87,
			"FORTISIP 2KCAL",0.68,
			"FORTISIP BOTTLE",	0.95,
			"FORTINI",0.88,
			"FORTINI COMPACT MULTIFIBRE",0.71,
			"FORTINI CREAMY FRUIT",	0.27,
			"FORTINI MULTIFIBRE", 0.39,
			"INFATRINI",0.83,
			"INFATRINI PEPTISORB",0.81,1
			)
			RETURN IF(RELATED(DIM_GEO_COUNTRY[Country])="Ireland",1,per_)
		lineageTag: 3cfef8e7-0741-4739-ab0a-1cc80a08b178
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition P&L_Pivot = m
		mode: import
		source = ```
				let
				    Source = Value.NativeQuery(Snowflake.Databases("danone.west-europe.azure.snowflakecomputing.com","PRD_SNS_UKI_ANL_WH",[Implementation="2.0", Role="PRD_SNS_UKI_USER"]){[Name="PRD_SNS_UKI"]}[Data], 
				    "
				    
				    
				  SELECT
				FT.SOURCE,
				FT.CONTRACT_ID,
				FT.CONTRACT_R_ID,
				FT.CURO_SUB_CONTRACT_ID,
				FT.SALES_CHANNEL_ID,
				FT.PRODUCT_ID,
				FT.GEOGRAPHY_ID,
				FT.Volumes_in_Units, --Invoice_Units,
				FT.Invoiced_Sales, --Total_Invoice,
				FT.FP10_VALUE,
				FT.FP10_PRICE,
				PRD.PRODUCT_CODE
				FROM (
				With MAX_MTH AS
				(
				SELECT
				TO_NUMBER(TO_VARCHAR(LAST_DAY(TO_DATE(MAX('202503')|| '01','YYYYMMDD')),'YYYYMMDD')) AS STARTDATE,
				TO_NUMBER(TO_VARCHAR(ADD_MONTHS(TO_DATE(MAX('202503')|| '01','YYYYMMDD'),-11),'YYYYMMDD')) AS ENDDATE,
				LAST_DAY(TO_DATE(MAX('202503')|| '01','YYYYMMDD'))::TIMESTAMP_TZ AS MONTHEND_TZ,
				DATEADD(DAY,-1,LAST_DAY(TO_DATE(MAX('202503')|| '01','YYYYMMDD')))::TIMESTAMP_TZ AS MONTHEND_TZ1,
				TO_DATE(MAX('202503')|| '01','YYYYMMDD')::TIMESTAMP_TZ AS MONTHSTART_TZ
				)
				,CCG_MAP AS
				(SELECT 'ANGUS HSCP' AS CCG_NAME,  'R149' AS CONTRACT_R_CODE UNION ALL
				SELECT 'CWM TAF MORG UNI' AS CCG_NAME,  'R215' AS CONTRACT_R_CODE UNION ALL
				SELECT 'DUMFRIES & GALLOWAY HSCP' AS CCG_NAME,  'R110' AS CONTRACT_R_CODE UNION ALL
				SELECT 'BETSI CADWALADR UNI' AS CCG_NAME,  'R485' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CITY AND HACKNEY CCG' AS CCG_NAME,  'R154' AS CONTRACT_R_CODE UNION ALL
				SELECT 'ABERDEEN CITY HSCP' AS CCG_NAME,  'R116' AS CONTRACT_R_CODE UNION ALL
				SELECT 'GUERNSEY' AS CCG_NAME,  'R479' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HEYWD MIDD ROCHD CCG' AS CCG_NAME,  'R171' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BRENT CCG' AS CCG_NAME,  'R169' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH EAST ESSEX CCG' AS CCG_NAME,  'R501' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS ASHFORD CCG' AS CCG_NAME,  'R032' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WINDS ASC MAIDEN CCG' AS CCG_NAME,  'R132' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BARKNG & DAGENHM CCG' AS CCG_NAME,  'R016' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LIVERPOOL CCG' AS CCG_NAME,  'R142' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LEEDS NORTH CCG' AS CCG_NAME,  'R138' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NEWCASTLE N & E CCG' AS CCG_NAME,  'R033' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BEDFORDSHIRE CCG' AS CCG_NAME,  'R018' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BARNSLEY CCG' AS CCG_NAME,  'R168' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BRIGHTON & HOVE CCG' AS CCG_NAME,  'R004' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH HAMPSHIRE CCG' AS CCG_NAME,  'R133' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS N & W READING CCG' AS CCG_NAME,  'R132' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORWICH CCG' AS CCG_NAME,  'R166' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CAMDEN CCG' AS CCG_NAME,  'R153' AS CONTRACT_R_CODE UNION ALL
				SELECT 'CARDIFF & VALE UNIVERSTY' AS CCG_NAME,  'R217' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CANNOCK CHASE CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'CHESHIRE CCG' AS CCG_NAME,  'R161' AS CONTRACT_R_CODE UNION ALL
				SELECT 'CWM TAF MORG UNIV LHB' AS CCG_NAME,  'R215' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS FAREHAM & GOSPRT CCG' AS CCG_NAME,  'R133' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS FYLDE & WYRE CCG' AS CCG_NAME,  'R137' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CHORLEY & S RIBB CCG' AS CCG_NAME,  'R172' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS EREWASH CCG' AS CCG_NAME,  'R022' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BRADFORD CITY CCG' AS CCG_NAME,  'R139' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HIGH WLD LEW HAV CCG' AS CCG_NAME,  'R031' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS MILTON KEYNES CCG' AS CCG_NAME,  'R152' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LAMBETH CCG' AS CCG_NAME,  'R037' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS E LEICESTR & RUT CCG' AS CCG_NAME,  'R045' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS TAMESIDE GLOSSOP CCG' AS CCG_NAME,  'R211' AS CONTRACT_R_CODE UNION ALL
				SELECT 'ABERDEENSHIRE HSCP' AS CCG_NAME,  'R116' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS ISLE OF WIGHT CCG' AS CCG_NAME,  'R134' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SCARBORO RYEDALE CCG' AS CCG_NAME,  'R098' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NEWHAM CCG' AS CCG_NAME,  'R154' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS EAST LANCASHIRE CCG' AS CCG_NAME,  'R150' AS CONTRACT_R_CODE UNION ALL
				-- SELECT 'NHS NEWCASTLE N & E CCG' AS CCG_NAME,  'R076' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NE HANTS & FARNM CCG' AS CCG_NAME,  'R027' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WALTHAM FOREST CCG' AS CCG_NAME,  'R016' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WANDSWORTH CCG' AS CCG_NAME,  'R008' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH CHESHIRE CCG' AS CCG_NAME,  'R209' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CASTLE PT & ROCH CCG' AS CCG_NAME,  'R136' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS KNOWSLEY CCG' AS CCG_NAME,  'R147' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS ROTHERHAM CCG' AS CCG_NAME,  'R167' AS CONTRACT_R_CODE UNION ALL
				SELECT 'DERBY & DERBYSHIRE CCG' AS CCG_NAME,  'R480' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS THANET CCG' AS CCG_NAME,  'R032' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BROMLEY CCG' AS CCG_NAME,  'R025' AS CONTRACT_R_CODE UNION ALL
				SELECT 'ANEURIN BEVAN' AS CCG_NAME,  'R484' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS N WEST SURREY CCG' AS CCG_NAME,  'R040' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS KINGSTON CCG' AS CCG_NAME,  'R008' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH NORFOLK CCG' AS CCG_NAME,  'R166' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH DURHAM CCG' AS CCG_NAME,  'R006' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LEEDS WEST CCG' AS CCG_NAME,  'R138' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS GREENWICH CCG' AS CCG_NAME,  'R522' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS MANSFLD & ASHFLD CCG' AS CCG_NAME,  'R014' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BURY CCG' AS CCG_NAME,  'R171' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HOUNSLOW CCG' AS CCG_NAME,  'R180' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS MEDWAY CCG' AS CCG_NAME,  'R135' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS COVENTRY & RUGBY CCG' AS CCG_NAME,  'R525' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS OLDHAM CCG' AS CCG_NAME,  'R171' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS S LINCOLNSHIRE CCG' AS CCG_NAME,  'R141' AS CONTRACT_R_CODE UNION ALL
				SELECT 'CLACKMAN & STIRLING HSCP' AS CCG_NAME,  'R111' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS MORECAMBE BAY CCG' AS CCG_NAME,  'R038' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NEWBURY AND DIST CCG' AS CCG_NAME,  'R132' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NENE CCG' AS CCG_NAME,  'R176' AS CONTRACT_R_CODE UNION ALL
				SELECT 'JERSEY' AS CCG_NAME,  'R019' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS E & N HERTS CCG' AS CCG_NAME,  'R164' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HAMB RICH WHITBY CCG' AS CCG_NAME,  'R006' AS CONTRACT_R_CODE UNION ALL
				SELECT 'HYWEL DDA' AS CCG_NAME,  'R488' AS CONTRACT_R_CODE UNION ALL
				SELECT 'EAST LOTHIAN HSCP' AS CCG_NAME,  'R117' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS COASTAL W SUSSEX CCG' AS CCG_NAME,  'R004' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SWALE CCG' AS CCG_NAME,  'R032' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTHAMPTON CCG' AS CCG_NAME,  'R009' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SALFORD CCG' AS CCG_NAME,  'R143' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HARROW CCG' AS CCG_NAME,  'R169' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HARINGEY CCG' AS CCG_NAME,  'R153' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HEREFORDSHIRE CCG' AS CCG_NAME,  'R174' AS CONTRACT_R_CODE UNION ALL
				SELECT 'ISLE OF MAN' AS CCG_NAME,  'R175' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS ISLINGTON CCG' AS CCG_NAME,  'R153' AS CONTRACT_R_CODE UNION ALL
				SELECT 'EDINBURGH HSCP' AS CCG_NAME,  'R117' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CORBY CCG' AS CCG_NAME,  'R176' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HORSHM & MID SUS CCG' AS CCG_NAME,  'R004' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SURREY DOWNS CCG' AS CCG_NAME,  'R008' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS OXFORDSHIRE CCG' AS CCG_NAME,  'R158' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH KIRKLEES CCG' AS CCG_NAME,  'R482' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BASLDN & BRENTWD CCG' AS CCG_NAME,  'R136' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CENTRAL LONDON CCG' AS CCG_NAME,  'R162' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS EAST SURREY CCG' AS CCG_NAME,  'R157' AS CONTRACT_R_CODE UNION ALL
				SELECT 'WEST LOTHIAN HSCP' AS CCG_NAME,  'R117' AS CONTRACT_R_CODE UNION ALL
				SELECT 'WEST DUNBARTONSHIRE HSCP' AS CCG_NAME,  'R112' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS REDBRIDGE CCG' AS CCG_NAME,  'R016' AS CONTRACT_R_CODE UNION ALL
				SELECT 'GLASGOW CITY HSCP' AS CCG_NAME,  'R112' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WIRRAL CCG' AS CCG_NAME,  'R219' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WOKINGHAM CCG' AS CCG_NAME,  'R132' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS IPSWICH & E SUFF CCG' AS CCG_NAME,  'R501' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS S GLOUCESTERSHRE CCG' AS CCG_NAME,  'R026' AS CONTRACT_R_CODE UNION ALL
				SELECT 'INVERCLYDE HSCP' AS CCG_NAME,  'R112' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HARDWICK CCG' AS CCG_NAME,  'R480' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS EAST STAFFORDSHR CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HARTLEPL & S-O-T CCG' AS CCG_NAME,  'R006' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HAVERING CCG' AS CCG_NAME,  'R016' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS DARLINGTON CCG' AS CCG_NAME,  'R006' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LEICESTER CITY CCG' AS CCG_NAME,  'R045' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH DERBYSHIRE CCG' AS CCG_NAME,  'R480' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WARRINGTON CCG' AS CCG_NAME,  'R013' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BLACKPOOL CCG' AS CCG_NAME,  'R137' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CRAWLEY CCG' AS CCG_NAME,  'R157' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BMNGHM CROSS CTY CCG' AS CCG_NAME,  'R001' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LUTON CCG' AS CCG_NAME,  'R018' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS GREATER PRESTON CCG' AS CCG_NAME,  'R172' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS REDD & BROMSGRV CCG' AS CCG_NAME,  'R529' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS GLOUCESTERSHIRE CCG' AS CCG_NAME,  'R030' AS CONTRACT_R_CODE UNION ALL
				SELECT 'FIFE HSCP' AS CCG_NAME,  'R148' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTHUMBERLAND CCG' AS CCG_NAME,  'R076' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NOTTINGHAM WEST CCG' AS CCG_NAME,  'R014' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOLIHULL CCG' AS CCG_NAME,  'R001' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST CHESHIRE CCG' AS CCG_NAME,  'R161' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS DORSET CCG' AS CCG_NAME,  'R020' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS KERNOW CCG' AS CCG_NAME,  'R131' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH SEFTON CCG' AS CCG_NAME,  'R142' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HAMMERSMTH FULHM CCG' AS CCG_NAME,  'R169' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CANTERBY & COAST CCG' AS CCG_NAME,  'R032' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS RUSHCLIFFE CCG' AS CCG_NAME,  'R014' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS TELFORD & WREKIN CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS DONCASTER CCG' AS CCG_NAME,  'R021' AS CONTRACT_R_CODE UNION ALL
				SELECT 'EAST AYRSHIRE HSCP' AS CCG_NAME,  'R159' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH MANCHESTER CCG' AS CCG_NAME,  'R512' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BIRMINGHAM S & C CCG' AS CCG_NAME,  'R001' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BRACKNLL & ASCOT CCG' AS CCG_NAME,  'R132' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HALTON CCG' AS CCG_NAME,  'R013' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS GTR HUDDERSFIELD CCG' AS CCG_NAME,  'R482' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTHERN DERBYSH CCG' AS CCG_NAME,  'R022' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTHWARK CCG' AS CCG_NAME,  'R037' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS DEVON CCG' AS CCG_NAME,  'R131' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS N LINCOLNSHIRE CCG' AS CCG_NAME,  'R121' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS MERTON CCG' AS CCG_NAME,  'R008' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NEWARK & SHERWD CCG' AS CCG_NAME,  'R014' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SWINDON CCG' AS CCG_NAME,  'R003' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH WORCS CCG' AS CCG_NAME,  'R529' AS CONTRACT_R_CODE UNION ALL
				SELECT 'ARGYLL & BUTE HSCP' AS CCG_NAME,  'R113' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WOLVERHAMPTON CCG' AS CCG_NAME,  'R524' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WYRE FOREST CCG' AS CCG_NAME,  'R529' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NORTH AYRSHIRE HSCP' AS CCG_NAME,  'R159' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NORTH LANARKSHIRE HSCP' AS CCG_NAME,  'R160' AS CONTRACT_R_CODE UNION ALL
				SELECT 'ORKNEY HEALTH & CARE' AS CCG_NAME,  'R118' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH TYNESIDE CCG' AS CCG_NAME,  'R007' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS TOWER HAMLETS CCG' AS CCG_NAME,  'R154' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS RICHMOND CCG' AS CCG_NAME,  'R008' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NE LINCOLNSHIRE CCG' AS CCG_NAME,  'R121' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CROYDON CCG' AS CCG_NAME,  'R008' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LINCOLNSHIRE E CCG' AS CCG_NAME,  'R141' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SW LINCOLNSHIRE CCG' AS CCG_NAME,  'R024' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BEXLEY CCG' AS CCG_NAME,  'R521' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH KENT COAST CCG' AS CCG_NAME,  'R032' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS GUILDFRD & WAVER CCG' AS CCG_NAME,  'R040' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS TRAFFORD CCG' AS CCG_NAME,  'R514' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LEEDS S & E CCG' AS CCG_NAME,  'R138' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SANDWLL W BMNGHM CCG' AS CCG_NAME,  'R532' AS CONTRACT_R_CODE UNION ALL
				SELECT 'MORAY HSCP' AS CCG_NAME,  'R116' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NOTTINGHAM N & E CCG' AS CCG_NAME,  'R014' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HILLINGDON CCG' AS CCG_NAME,  'R165' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS THURROCK CCG' AS CCG_NAME,  'R136' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST LANCASHIRE CCG' AS CCG_NAME,  'R146' AS CONTRACT_R_CODE UNION ALL
				SELECT 'RENFREWSHIRE HSCP' AS CCG_NAME,  'R112' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTHEND CCG' AS CCG_NAME,  'R136' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LINCOLNSHIRE W CCG' AS CCG_NAME,  'R141' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS ST HELENS CCG' AS CCG_NAME,  'R147' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HASTINGS & ROTHR CCG' AS CCG_NAME,  'R031' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH MANCHESTER CCG' AS CCG_NAME,  'R171' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BRISTOL CCG' AS CCG_NAME,  'R026' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS STAFFORD & SURR CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS STOKE ON TRENT CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS E RIDING OF YORK CCG' AS CCG_NAME,  'R036' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH SOMERSET CCG' AS CCG_NAME,  'R026' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS EASTERN CHESHIRE CCG' AS CCG_NAME,  'R209' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SLOUGH CCG' AS CCG_NAME,  'R132' AS CONTRACT_R_CODE UNION ALL
				SELECT 'FALKIRK HSCP' AS CCG_NAME,  'R111' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NOTTINGHAM CITY CCG' AS CCG_NAME,  'R014' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SHROPSHIRE CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'DUNDEE HSCP' AS CCG_NAME,  'R149' AS CONTRACT_R_CODE UNION ALL
				SELECT 'EAST RENFREWSHIRE HSCP' AS CCG_NAME,  'R112' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CHILTERN CCG' AS CCG_NAME,  'R152' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS STOCKPORT CCG' AS CCG_NAME,  'R214' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS AYLESBURY VALE CCG' AS CCG_NAME,  'R152' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS DUDLEY CCG' AS CCG_NAME,  'R523' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SUTTON CCG' AS CCG_NAME,  'R008' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTHPT & FORMBY CCG' AS CCG_NAME,  'R146' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS EALING CCG' AS CCG_NAME,  'R163' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS DARTF GRVES SWAN CCG' AS CCG_NAME,  'R135' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS VALE OF YORK CCG' AS CCG_NAME,  'R098' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS VALE ROYAL CCG' AS CCG_NAME,  'R209' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BRADFORD DIST CCG' AS CCG_NAME,  'R139' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH READING CCG' AS CCG_NAME,  'R132' AS CONTRACT_R_CODE UNION ALL
				SELECT 'WESTERN ISLES HSCP' AS CCG_NAME,  'R114' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH TEES CCG' AS CCG_NAME,  'R006' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS DURH EASING SEDG CCG' AS CCG_NAME,  'R006' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HULL CCG' AS CCG_NAME,  'R036' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WARWICKSHIRE N CCG' AS CCG_NAME,  'R525' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST ESSEX CCG' AS CCG_NAME,  'R034' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST HAMPSHIRE CCG' AS CCG_NAME,  'R009' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST KENT CCG' AS CCG_NAME,  'R135' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS W LEICESTERSHIRE CCG' AS CCG_NAME,  'R045' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WAKEFIELD CCG' AS CCG_NAME,  'R170' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WALSALL CCG' AS CCG_NAME,  'R531' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST LONDON CCG' AS CCG_NAME,  'R169' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST NORFOLK CCG' AS CCG_NAME,  'R166' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WILTSHIRE CCG' AS CCG_NAME,  'R003' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WEST SUFFOLK CCG' AS CCG_NAME,  'R151' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS WIGAN BOROUGH CCG' AS CCG_NAME,  'R182' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SUNDERLAND CCG' AS CCG_NAME,  'R007' AS CONTRACT_R_CODE UNION ALL
				SELECT 'SCOTTISH BORDERS HSCP' AS CCG_NAME,  'R115' AS CONTRACT_R_CODE UNION ALL
				SELECT 'SHETLAND HSCP' AS CCG_NAME,  'R119' AS CONTRACT_R_CODE UNION ALL
				SELECT 'SOUTH AYRSHIRE HSCP' AS CCG_NAME,  'R159' AS CONTRACT_R_CODE UNION ALL
				SELECT 'SOUTH LANARKSHIRE HSCP' AS CCG_NAME,  'R160' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS N STAFFORDSHIRE CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS MID ESSEX CCG' AS CCG_NAME,  'R136' AS CONTRACT_R_CODE UNION ALL
				SELECT 'SWANSEA BAY UNI' AS CCG_NAME,  'R130' AS CONTRACT_R_CODE UNION ALL
				-- SELECT 'SWANSEA BAY UNI' AS CCG_NAME,  'R130' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CAMBRDG & PBORO CCG' AS CCG_NAME,  'R024' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BASSETLAW CCG' AS CCG_NAME,  'R021' AS CONTRACT_R_CODE UNION ALL
				SELECT 'Central Manchester (Paediatrics)' AS CCG_NAME,  'R145' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SE STAFFS & SEIS CCG' AS CCG_NAME,  'R140' AS CONTRACT_R_CODE UNION ALL
				SELECT 'PERTH & KINROSS HSCP' AS CCG_NAME,  'R149' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BARNET CCG' AS CCG_NAME,  'R153' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BANES CCG' AS CCG_NAME,  'R003' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS LEWISHAM CCG' AS CCG_NAME,  'R037' AS CONTRACT_R_CODE UNION ALL
				SELECT 'MIDLOTHIAN HSCP' AS CCG_NAME,  'R117' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH NORFOLK CCG' AS CCG_NAME,  'R166' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS PORTSMOUTH CCG' AS CCG_NAME,  'R133' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SHEFFIELD CCG' AS CCG_NAME,  'R010' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BOLTON CCG' AS CCG_NAME,  'R144' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS AIRED WHARF CRVE CCG' AS CCG_NAME,  'R029' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS ENFIELD CCG' AS CCG_NAME,  'R153' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SURREY HEATH CCG' AS CCG_NAME,  'R027' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS GT YARMTH & WAVE CCG' AS CCG_NAME,  'R166' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CALDERDALE CCG' AS CCG_NAME,  'R482' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HERTS VALLEYS CCG' AS CCG_NAME,  'R164' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS HARROGT & RURAL CCG' AS CCG_NAME,  'R002' AS CONTRACT_R_CODE UNION ALL
				SELECT 'HIGHLAND HSCP' AS CCG_NAME,  'R113' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NEWCASTLE WEST CCG' AS CCG_NAME,  'R076' AS CONTRACT_R_CODE UNION ALL
				SELECT 'EAST DUNBARTONSHIRE HSCP' AS CCG_NAME,  'R112' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOMERSET CCG' AS CCG_NAME,  'R020' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS SOUTH WARWICKSHR CCG' AS CCG_NAME,  'R525' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS S EASTERN HANTS CCG' AS CCG_NAME,  'R133' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS CENTRAL MANCHSTR CCG' AS CCG_NAME,  'R514' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS EASTB HAILS SEAF CCG' AS CCG_NAME,  'R031' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS BLACKB WTH DARWN CCG' AS CCG_NAME,  'R150' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH TYNESIDE CCG' AS CCG_NAME,  'R076' AS CONTRACT_R_CODE UNION ALL
				SELECT 'POWYS TEACHING' AS CCG_NAME,  'R491' AS CONTRACT_R_CODE UNION ALL
				SELECT 'BRADFD DIST & CRAVEN CCG' AS CCG_NAME,  'R139' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS NORTH CUMBRIA CCG' AS CCG_NAME,  'R076' AS CONTRACT_R_CODE UNION ALL
				SELECT 'HEREFORDSHRE & WORCS CCG' AS CCG_NAME,  'R174' AS CONTRACT_R_CODE UNION ALL
				SELECT 'NHS GATESHEAD CCG' AS CCG_NAME,  'R033' AS CONTRACT_R_CODE
				),
				CTR_ID AS (
				SELECT CONTRACT_R_CODE, D.CONTRACT_ID, ROW_NUMBER() OVER(PARTITION BY CONTRACT_R_CODE ORDER BY D.CONTRACT_ID ASC) AS TES  FROM CCG_MAP
				LEFT JOIN PRD_SNS_UKI.SNS_UKI_DSP_SNU.DIM_MEDICAL_CONTRACT D ON CCG_MAP.CONTRACT_R_CODE = D.GROUP_ID
				),
				CTR_ID2 AS (
				SELECT CONTRACT_R_CODE,CONTRACT_ID FROM CTR_ID WHERE TES = 1)
				
				
				Select  
				'Homeward Sales' as SOURCE,
				MD.CONTRACT_ID,
				MD.CONTRACT_R_ID,
				PA.CURO_SUB_CONTRACT_ID,
				S.SALES_CHANNEL_ID,
				S.PRODUCT_ID,
				S.GEOGRAPHY_ID,
				SUM(INVOICE_ACTUAL_QUANTITY_SINGLE)::NUMBER(38,2) as Volumes_in_Units, --Invoice_Units,
				SUM(SUBTOTAL_5_PRICING_COND_GBP)::NUMBER(38,2) + sum(VAT_VALUE_GBP)::NUMBER(38,2) as Invoiced_Sales, --Total_Invoice,
				SUM(INVOICE_ACTUAL_QUANTITY_SINGLE* P.FP10_PRICE)::NUMBER(38,2) as FP10_PRICE,
				P.FP10_PRICE AS FP10_VALUE
				  FROM  SNS_UKI_DSP_SNU.FACT_SALES_INVOICE S
				  LEFT JOIN  SNS_UKI_DSP_SNU.DIM_PRODUCT P ON S.PRODUCT_ID= P.PRODUCT_ID
				  LEFT JOIN SNS_UKI_DSP_SNU.DIM_CURO_PATIENT PA ON PA.PATIENT_ID=S.PATIENT_ID
				  LEFT JOIN PRD_SNS_UKI.SNS_UKI_DSP_SNU.DIM_MEDICAL_CONTRACT MD ON MD.CURO_SUB_CONTRACT_ID=PA.CURO_SUB_CONTRACT_ID
				  WHERE S.INVOICE_DATE_ID <=(SELECT STARTDATE from MAX_MTH)  and S.INVOICE_DATE_ID  >= (SELECT ENDDATE from MAX_MTH) --last iqvia year
				  -- WHERE SUBSTR(S.INVOICE_DATE_ID,1,6)=SUBSTR((SELECT STARTDATE from MAX_MTH),1,6)  -- last IQVIA month data
				  -- WHERE S.INVOICE_DATE_ID <= 20241031 and S.INVOICE_DATE_ID >= 20231101
				  and S.SALES_CHANNEL_ID in (2)
				  and S.product_id <> 2071
				  and S.ORDER_REASON_CODE not in ('ZMA', 'ZIL', 'ZMK', 'ZIT')
				  group by 
				  SOURCE,
				  MD.CONTRACT_ID,
				  MD.CONTRACT_R_ID,
				  PA.CURO_SUB_CONTRACT_ID,
				  S.SALES_CHANNEL_ID,
				  S.PRODUCT_ID,
				  S.GEOGRAPHY_ID,
				  P.FP10_PRICE
				  
				UNION ALL
				
				select 'Hospital' as Source,
				S.CONTRACT_ID,
				MD.CONTRACT_R_ID,
				PA.CURO_SUB_CONTRACT_ID,
				S.SALES_CHANNEL_ID,
				S.PRODUCT_ID,
				S.GEOGRAPHY_ID,
				SUM(QUANTITY_PIECE)::NUMBER(38,2) as Volumes_in_Units,--as Channel_Sales_Singles,
				SUM(SALES_VALUE_GBP)::NUMBER(38,2) as Invoiced_Sales,-- Channel_Sales_GBP,
				sum(QUANTITY_PIECE* P.FP10_PRICE)::NUMBER(38,2) as FP10_PRICE,
				P.FP10_PRICE AS FP10_VALUE
				FROM  SNS_UKI_DSP_SNU.FACT_CHANNEL_SALES S
				LEFT JOIN  SNS_UKI_DSP_SNU.DIM_PRODUCT P
				ON S.PRODUCT_ID= P.PRODUCT_ID
				LEFT JOIN SNS_UKI_DSP_SNU.DIM_CURO_PATIENT PA ON S.PATIENT_ID=PA.PATIENT_ID
				LEFT JOIN PRD_SNS_UKI.SNS_UKI_DSP_SNU.DIM_MEDICAL_CONTRACT MD ON MD.CONTRACT_ID=S.CONTRACT_ID
				WHERE DATE_ID <=(SELECT STARTDATE from MAX_MTH)  and DATE_ID  >= (SELECT ENDDATE from MAX_MTH) and S.sales_channel_id = 1  -- whole 1 year data
				-- WHERE SUBSTR(DATE_ID,1,6)=SUBSTR((SELECT STARTDATE from MAX_MTH),1,6) and S.sales_channel_id = 1  -- last IQVIA month data
				-- WHERE DATE_ID <= 20241031 and DATE_ID >= 20231101 AND S.sales_channel_id = 1
				group by 
				SOURCE,
				S.CONTRACT_ID,
				MD.CONTRACT_R_ID,
				PA.CURO_SUB_CONTRACT_ID,
				S.SALES_CHANNEL_ID,
				S.PRODUCT_ID,
				S.GEOGRAPHY_ID,
				P.FP10_PRICE
				
				UNION ALL
				
				SELECT
				   'Community' as SOURCE,
				    CTR_ID2.CONTRACT_ID,
				    MD.CONTRACT_R_ID,
				    PA.CURO_SUB_CONTRACT_ID,
				    A.SALES_CHANNEL_ID,
				    A.PRODUCT_ID,
				    A.GEOGRAPHY_ID,
				    SUM(QUANTITY_PIECE)::NUMBER(38,2) as Volumes_in_Units,-- Community_Singles,
				    SUM(SALES_VALUE_GBP)::NUMBER(38,2) as Invoiced_Sales, --Community_Value_in_GBP
				    0 AS FP10_PRICE,
				    B.FP10_PRICE AS FP10_VALUE
				FROM
				     SNS_UKI_DSP_SNU.FACT_CHANNEL_SALES_MONTHLY A
				LEFT JOIN SNS_UKI_DSP_SNU.DIM_CURO_PATIENT PA ON A.PATIENT_ID=PA.PATIENT_ID
				LEFT JOIN SNS_UKI_DSP_SNU.DIM_GEO_TERRITORY GEO ON A.GEOGRAPHY_ID = GEO.GEO_TERRITORY_ID
				LEFT JOIN SNS_UKI_DSP_SNU.DIM_GEO_CCG   CCG ON GEO.GEO_CCG_ID = CCG.GEO_CCG_ID
				LEFT JOIN CCG_MAP CCG_MAP ON CCG.CCG_NAME = CCG_MAP.CCG_NAME
				LEFT JOIN CTR_ID2 ON CTR_ID2.CONTRACT_R_CODE = CCG_MAP.CONTRACT_R_CODE
				join SNS_UKI_DSP_SNU.DIM_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
				LEFT JOIN PRD_SNS_UKI.SNS_UKI_DSP_SNU.DIM_MEDICAL_CONTRACT MD ON MD.CONTRACT_ID=CTR_ID2.CONTRACT_ID
				join SNS_UKI_DSP_SNU.DIM_PRODUCT_HIER_LOCAL_6 C ON B.PROD_HIER_LOCAL_6_ID = C.PROD_HIER_LOCAL_6_ID
				join SNS_UKI_DSP_SNU.DIM_PRODUCT_HIER_LOCAL_5 D ON C.PROD_HIER_LOCAL_5_ID = D.PROD_HIER_LOCAL_5_ID
				join SNS_UKI_DSP_SNU.DIM_PRODUCT_HIER_LOCAL_4 E ON D.PROD_HIER_LOCAL_4_ID = E.PROD_HIER_LOCAL_4_ID
				join SNS_UKI_DSP_SNU.DIM_PRODUCT_HIER_LOCAL_3 F ON E.PROD_HIER_LOCAL_3_ID = F.PROD_HIER_LOCAL_3_ID AND F.PROD_HIER_LOCAL_3_ID <> 5675
				join SNS_UKI_DSP_SNU.DIM_PRODUCT_HIER_LOCAL_2 G ON F.PROD_HIER_LOCAL_2_ID = G.PROD_HIER_LOCAL_2_ID AND F.PROD_HIER_LOCAL_2_ID IN (745,6,11,746)
				WHERE to_char(MONTH_ID * 100 + 1) >= (SELECT ENDDATE FROM MAX_MTH) AND to_char(MONTH_ID * 100 + 1) <= (SELECT STARTDATE FROM MAX_MTH)  --last iqvia year
				  -- WHERE MONTH_ID=SUBSTR((SELECT STARTDATE from MAX_MTH),1,6)  -- last IQVIA month data
				AND SALES_CHANNEL_ID =3
				group by 
				SOURCE,
				CTR_ID2.CONTRACT_ID,
				MD.CONTRACT_R_ID,
				PA.CURO_SUB_CONTRACT_ID,
				SALES_CHANNEL_ID,
				A.PRODUCT_ID,
				A.GEOGRAPHY_ID,
				B.FP10_PRICE
				) FT LEFT JOIN SNS_UKI_DSP_SNU.DIM_PRODUCT PRD ON FT.PRODUCT_ID = PRD.PRODUCT_ID
				
				    ", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"PRODUCT_CODE", "SKU"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

