table Product_classification
	lineageTag: 5f7f024b-7e16-4115-8791-4a9a7cba8f6a

	column 'Commercial 6'
		dataType: string
		lineageTag: a3818a12-04c7-4580-aa54-f9674429aa76
		summarizeBy: none
		sourceColumn: Commercial 6

		annotation SummarizationSetBy = Automatic

	column Classification
		dataType: string
		lineageTag: c1ce2e71-1703-4eab-837a-1a426abda9c4
		summarizeBy: none
		sourceColumn: Classification

		annotation SummarizationSetBy = Automatic

	partition Product_classification = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rZhbb9s2FID/CpHnJvAlXrpHWqItzpTIklQSo+hDthhtgWIO4hTF/v1IUZIlWSSPsj0lML9z5eHhoT5/vtpwqWkiSU5QwnPBiCZovlhtrz5cJcfXA+KFuvryoeYUFRWFE402dC0rNGdRVkiukdJYaiKR+WUHlDM2pojlJdPU+bWYzWD6DTu0gDySf5RJSHG13NMVdmICutglmAFjgmV2QlbXXGsWy2gNiXWEk7jYgrOUE2jQtsAILSaUo6XfUZGNyG8QIfKoJY5E4JgJtbDn21JaR/bRTfHFezsl4qEwKHLBcKHRGiuSRnzcyJJqlBKliIlqvpr5O091vJszi+95KfcR5Y3vMCq+CUm5php79BWlljSVtNgFj4wgot75gsjtHmXCYwszviUdW08/jl8Pf/fWVoG1xcq/NihML6EyrhW69WIe4fkspnmwRosNNskraFtW4unwfELXKCN0M0AatwPIKo64beByDdAX1jSPG+tW1hhZlaJVdTO7cOf0/aXHxNbNXY7zfX2ujG/bEFuf8c7FOdyAocjIHetDVc65zmgctGF3D3eUh/sYQ0evgCGcYEVNQ0O/z5DgDymRyp4um1j+9u3wej6ydoDCtpFQeW0aym0IyinbqQzvSHtSPcraLAYxRj+V9Nxs+5AkBWW8QHc3qzbIIaEENUnxLAtJrrnwaHcjJO5ku7+e40czHDGkSmEyrTgr17Y5rnaXyfGgs5E8Nij75HHLo+tmzK7gbG9HrGAW7T1BN1iihZuPIebmy4Xfmism019HwlMJLlLqCiSnj+jjiElz41BG1XlwN9Vspqt5uw/pP6eXb09fvz+F8EUz74/TrpE4dNlc0ONoHY85WGg5i3MKJxmxA6ufTBgx+Z7fBfxro3GPGEbuzdS4DMfUyrjruiMTSJtLhGNvw4lwbi9jgE1UOLYKq/MUVdfk82Ys9KZPNDXn3GfHX+iv4+kNvRx/PR9eT6OoUxdEa9OrOzAZ19mvEoCAOywQHyqw1/oDUtVcp0z3rKe6ZrjAzz9/vCH9889DH8vt0FzpBIBAnSnF9s95ZGxHLJ8EyAN364FUzWO6GH8wXS+lZR7XmPAiIYWZA7V5H0TT1JkMoFvQEYHFWGd2EtwZMwYDv09Q8T2OOl9BwEArFua0MrVOjcoHbIs+ine2E6Z/boI/N9buCDZ5t2IC3c2awk73JCpRfdkSrFTIvnvMeMWFWQGcqfrNWYlCjFQPVPMca15jXrZ918A6QItnBNRW+jww+51qALacbnqm0d3Kiwni9B6bTpQ2/RUuYL8ETJOopkf7C3xL3tuNYKXrkYuJ+c95tAPZZjWlMVwIwKsT2D87uba1k9Ft1l6y9v+msv4vPfEuOntvdmtz0ItDm+cFlink3qjJmMqP/9HzYSGGLlPzcrcX1KXk8MvPhVgUqHV6OW0Hl6CmlpjgXiszJZYp7Ht8iaWi0X2u/ikuD7/y+FyOcmfzUIcvkxE1Ml5uUTEvsKOFed3YD6L1818JklBsXnMabbbuE0DvS0JacvvNwEtnRGDJfeq+/As=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Commercial 6" = _t, Classification = _t]),
				    #"Sorted Rows" = Table.Sort(Source,{{"Commercial 6", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

